spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CRMOnline?useSSL=false&serverTimezone=UTC
    username: root 
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080