CREATE TABLE IF NOT EXISTS HT_UserModulePermission (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    User_Id INT UNSIGNED NOT NULL,
    ModuleKey VARCHAR(80) NOT NULL,
    CanView TINYINT(1) NOT NULL DEFAULT 0,
    CanRead TINYINT(1) NOT NULL DEFAULT 0,
    CanWrite TINYINT(1) NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Id),
    UNIQUE KEY UK_HT_UserModulePermission_User_Module (User_Id, ModuleKey),
    CONSTRAINT FK_HT_UserModulePermission_User
        FOREIGN KEY (User_Id) REFERENCES HT_User(Id)
        ON DELETE CASCADE
);

INSERT INTO HT_UserModulePermission (User_Id, ModuleKey, CanView, CanRead, CanWrite)
SELECT u.Id, m.ModuleKey, 1, 1, 1
FROM HT_User u
JOIN (
    SELECT 'LEAD' AS ModuleKey UNION ALL
    SELECT 'KHACH_HANG' UNION ALL
    SELECT 'CO_HOI' UNION ALL
    SELECT 'HOAT_DONG' UNION ALL
    SELECT 'BAO_GIA' UNION ALL
    SELECT 'HOP_DONG' UNION ALL
    SELECT 'HOA_DON' UNION ALL
    SELECT 'TAI_CHINH' UNION ALL
    SELECT 'BAO_CAO' UNION ALL
    SELECT 'SAN_PHAM' UNION ALL
    SELECT 'TICKET' UNION ALL
    SELECT 'NHAN_VIEN'
) m
WHERE u.Id = 1
ON DUPLICATE KEY UPDATE
    CanView = VALUES(CanView),
    CanRead = VALUES(CanRead),
    CanWrite = VALUES(CanWrite),
    UpdatedAt = CURRENT_TIMESTAMP;
